### ISSUE TITLE
Does Fantasia Append "Front"/"Side" to prompts?

### ISSUE THREAD

**Issue by JulianKnodt** [Gorilla-Lab-SCUT/Fantasia3D#11]
I was wondering whether Fantasia also appends "front" and "side" to their text prompts as a function of view angle? I don't think this was specified in the paper. I assume that it follows Magic3D and Dreamfusion, but just wanted to check.

**Comment by ARuiChen** [comment]
Yes, see #1 for more details.

**Comment by JulianKnodt** [comment]
Cheers, thanks!
Might be worth making a FAQ so you don't have to answer repeat questions
