### ISSUE TITLE
Quality assesment regarding threestudio re-implementation

### ISSUE THREAD

**Issue by jason718** [Gorilla-Lab-SCUT/Fantasia3D#12]
Have you guys checked the reimplementation in threestudio https://github.com/threestudio-project/threestudio? Is their code implemented correct? And how does their perform compared to your code? Is it better or worse. 

Thanks for the great work again!

**Comment by ARuiChen** [comment]
Thanks for the kind words! Their reproduction results look great, but I haven't actually run their code yet. I have been busy optimizing our code recently and have made significant improvements in performance and GPU memory usage.
