### ISSUE TITLE
 Inquiry about Running Text-to-3D Function and Availability of Pretrained Weights

### ISSUE THREAD

**Issue by angrypenguinpng** [Gorilla-Lab-SCUT/Fantasia3D#13]
Dear Fantasia3D Team,

I recently came across your fascinating project, Fantasia3D, on GitHub and I'm very interested in exploring it further.

I have a couple of questions that I hope you could help me with:

Could you provide more detailed instructions on how to run the text-to-3D function? I've read through the README file, but I would appreciate if you could provide a simple example to help me get started.

I noticed that the repository currently does not include any pretrained weights. Are there any plans to release pretrained weights in the future? Having access to these weights would be very helpful for those of us who want to use your model without having to train it from scratch.

Thank you in advance for your time and assistance. I'm looking forward to exploring Fantasia3D more!

**Comment by ARuiChen** [comment]
Hi, @blueangel1313 !  Thanks for your interest in our work!
Our method generates 3D using the 2D stable diffusion whose pre-trained weights have been released in huggingface. Fantasia3D, [DreamFusion](https://dreamfusion3d.github.io/), and [Magic3D](https://research.nvidia.com/labs/dir/magic3d/) are all optimization-based methods. Therefore, it is not possible to quickly infer and generate 3D models after training like [shape-e](https://github.com/openai/shap-e) and [point-e](https://github.com/openai/point-e). However, optimization-based methods often produce high-quality results on a single instance. Fantasia3D can seamlessly interface with these methods that can quickly generate 3D models by fine-tuning rough models using our user-guided generation. We recommend you read our paper for more details.

**Comment by angrypenguinpng** [comment]
Thank you for your detailed response! 

Based on your insights, I was wondering if you believe it would be possible to use any of the learnings you had to fine-tune the pretrained SHAP-E model? I'm curious about whether we can combine the speed of SHAP-E with the refinement capabilities of Fantasia3D to create a high-quality, yet efficient, 3D model that can run smoothly on consumer-grade hardware.

Apologies if this question seems a bit naive - I'm still learning about the intricacies of 3D model generation, but I find it really intriguing!

Your work and expertise is greatly appreciated. Looking forward to hearing your insights.

**Comment by ARuiChen** [comment]
To be precise, Fantasia3D can directly optimize the rough mesh generated by shape-e, rather than fine-tuning their model weights. Compared to deforming an ellipsoid to the target shape, optimizing from a rough mesh can greatly accelerate convergence. It takes about 15 minutes in 3090 and 10 minutes in 4090 to generate a new shape without texture.

**Comment by angrypenguinpng** [comment]
that makes sense! Thanks :D
