### ISSUE TITLE
Leverage Magic3D?

### ISSUE THREAD

**Issue by LifeIsStrange** [Gorilla-Lab-SCUT/Fantasia3D#2]
Hi, your results are extremely impressive!!
However I was wondering, stable-dreamfusion has recently gotten a significant increase in speed and accuracy/resolution via Magic3D from Nvidia, I wonder if their optimization can be applied to your project too https://research.nvidia.com/labs/dir/magic3d/
@ARuiChen 

While I'm at it, other very recent papers of interest are:
https://github.com/junshutang/Make-It-3D
and
https://news.ycombinator.com/item?id=35358360

a great feed is https://paperswithcode.com/task/text-to-3d

**Comment by ARuiChen** [comment]
Hi, @LifeIsStrange!
Magic3D is actually one of our baselines. The other two methods you mentioned use Nerf representation, which is different from DMtet representation. The main difference is that Nerf’s optimization relies on volume rendering, while Dmtet’s optimization uses surface rendering. That said, I still have to examine these two papers carefully to see if there are any ideas that I can borrow from. 
Thank you for your attention to our work!

**Comment by ARuiChen** [comment]
closed this as [completed](https://github.com/NVlabs/nvdiffrec/issues?)
