### ISSUE TITLE
About perturbed_normal

### ISSUE THREAD

**Issue by ashawkey** [Gorilla-Lab-SCUT/Fantasia3D#23]
Hi, I wonder why this `perturbed_nrm` is set to `None` here? If I understand correctly, this should be the part to learn the tangent space normal variation in paper?
https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/4b5b14f30e7ef6589571f577ec566d1eecb6d5e2/render/render.py#L74

P.S. there are some unnecessary `import` not included in `requirements.txt`:
https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/4b5b14f30e7ef6589571f577ec566d1eecb6d5e2/geometry/dmtet.py#L16
https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/4b5b14f30e7ef6589571f577ec566d1eecb6d5e2/train.py#L37

**Comment by ARuiChen** [comment]
Hi, @ashawkey !
For geometry modeling, there is no need to learn the tangent space normal variation.
For appearance modeling, the user can choose to whether to use this term. I forgot to set this term as an optional parameter. I will update it in the next commit. Thanks for reminding me!

**Comment by ashawkey** [comment]
Thanks for the quick reply! 
I'm also curious that do you observe improvement in appearance modeling with trainable normal variation (e.g., high frequency surface details)?

**Comment by ARuiChen** [comment]
This term is beneficial for appearances with complex textures. But for simple appearances such as "a highly detailed stone bust of Theodoros Kolokotronis" or "Michelangelo style statue of dog reading news on a cellphone", adding it can actually make the results dirty.

**Comment by ashawkey** [comment]
Thanks! Looking forward to see the update.
