### ISSUE TITLE
issues about imageio version 

### ISSUE THREAD

**Issue by florinshen** [Gorilla-Lab-SCUT/Fantasia3D#26]
The imageio 2.9.0 provided in requirments file will crack down when running apprerance modeling mode:

ValueError: Could not find a backend to open `data/irrmaps/mud_road_puresky_4k.hdr`` with iomode `ri`.

Could you plz provide the imageio version in your current envs ?

**Comment by ShudaLi** [comment]
The problem can be fixed using cv2. See the following. Will try to do a PR for it.   
`import cv2
 return cv2.imread(fn, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)`

**Comment by ShudaLi** [comment]
Cannot fire PR for no permission, but hopefully you get the point.

**Comment by florinshen** [comment]
thank you for your reply. this modification works well on this bug.
