### ISSUE TITLE
blender rendering

### ISSUE THREAD

**Issue by Crane-YU** [Gorilla-Lab-SCUT/Fantasia3D#28]
Hi @ARuiChen ,
Thx for sharing the work, can you share the blender script that you used for rendering the mesh files?

**Comment by ARuiChen** [comment]
Hi @Crane-YU ,
You can refer to https://github.com/NVlabs/nvdiffrecmc#use-the-extracted-3d-models-in-blender. We have modified and added some code to the script but do not prepare to release it temporarily.

**Comment by ARuiChen** [comment]
Hi @Crane-YU ,
I have added the uv padding in the code. Now you don't need to perform UV padding yourself in blender.
