### ISSUE TITLE
xformer Offline Installation

### ISSUE THREAD

**Issue by Daybreak-Zheng** [Gorilla-Lab-SCUT/Fantasia3D#29]
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/2d1935e0-5da7-4b1f-9300-7ae8a656bda8)
I encountered an error during the offline installation of xformers. How can I resolve it? I look forward to your response.

**Comment by bennyguo** [comment]
You don't really need xformers for this to work :)

**Comment by ARuiChen** [comment]
I have never seen such an error, you can try to solve it yourself or not install it :) The effect of xformers is to accelerate training, and the code can still work without it.

**Comment by Daybreak-Zheng** [comment]
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/45732e9c-4575-4874-9191-192a33012e0e)
When running the training command, I encountered this error. How can I resolve it?
Additionally, I am using the Docker environment provided by you.

**Comment by ARuiChen** [comment]
Your driver may lack some opengl files. You need to check if there are any libEGL_nvidia.so files that match the Driver Version
```python
ls /usr/lib/x86_64-linux-gnu | grep -i libegl
``` 
In my server, I can get the information as follow:
![1](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/128572637/2178f61e-e4f0-4e08-85e2-c5f8d124b001)
My driver version is 510.60.02 so there is the matching file.
You should reinstall your Nvidia driver if there is no matching file.
Or you can replace the line  glctx = dr.RasterizeGLContext() to glctx = dr.RasterizeCudaContext() in [train.py](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/main/train.py#L587)

**Comment by Daybreak-Zheng** [comment]
![e4a295e61d2638b3e2fd7f9b92ad633](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/8a041d7f-e498-4fbe-9525-59660159559d)
How to solve this issue when training the appearance model?

**Comment by ARuiChen** [comment]
try #26

**Comment by Daybreak-Zheng** [comment]
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/b311a209-e2ff-40e9-928d-2e1e7bea248f)
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/7499688a-df0a-424b-9868-d617cc4d7791)
After training according to your instructions, I have a feeling that the generated results are not very good. Could you please let me know if this meets your expectations, or if I have made any mistakes in my operation?

**Comment by ARuiChen** [comment]
How many GPUs did you use? 4 or 8 GPUs are recommended. I use 8 GPUs just now and it works well. 

https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/128572637/d08a4ec6-3457-4529-9c25-81adc3e5ba2e

**Comment by Daybreak-Zheng** [comment]
Does the number of GPUs affect the results? I used six GPUs. RTX3090.

**Comment by ARuiChen** [comment]
The sampling stratery illustated in the suplementary is very important to alleviate janus problem, but I just implemented it in the case of 4 or 8 GPUs. You can modify it by yourself  in https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/main/dataset/dataset_mesh.py#L77

**Comment by Daybreak-Zheng** [comment]
May I ask what parameters you used for your experimental setup, such as 'iter' and 'coarse_iter'?

**Comment by ARuiChen** [comment]
Same as the configs provided in this repository. Please feel free to ask questions and show your generated results, and I will try my best to use my experience to help you solve it.

**Comment by Daybreak-Zheng** [comment]
[video_log.zip](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/files/12061023/video_log.zip)
Do these generated results meet your expectations? I didn't modify any parameters and trained it using eight RTX 3090 GPUs.

**Comment by ARuiChen** [comment]
This looks like the result of strategy 0 in appearance modeling. The light and shadow changes generated by strategy 0 will be relatively strong. If you want a smoother result, you can try strategy 1 or 2. Please let me know if this has solved your problem after trying different strategies.

**Comment by Daybreak-Zheng** [comment]
[video_log2.zip](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/files/12061405/video_log2.zip)
Hi, This is the result generated using strategy 1 in appearance modeling, but it seems that the shape is not quite realistic.

**Comment by ARuiChen** [comment]
The appearance generated using strategy 1 is smoother and more comfortable than strategy 0 which generates a more realistic appearance. If you are still dissatisfied, I have the following two suggestions:
1、 try strategy 2 
2、 try to add "a DSLR photo of ...."  before the text prompt using strategy 0 or 1 or 2.

**Comment by Daybreak-Zheng** [comment]
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/8ab95758-d574-4773-a740-bee295e3b1ec)
Is it normal for all these loss values to be zero during the training process?
I always feel that the results of my actual training deviate from the results in your paper, and I'm not sure where the problem lies.
such as ice cream:
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/56215b85-a4e1-4dfb-bf27-5bd86936aa52)
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/9fd6ae9e-278d-4cf1-a4b9-734f85e82411)

and car:
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/db387fa7-0703-42c5-a1a3-76e4a4938659)
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/44741080/a1974048-840e-4674-9983-509ced10e63a)

**Comment by ARuiChen** [comment]
The optimized results of sds loss have diversity and randomness, and you cannot obtain completely consistent results in every optimization. Moreover, different seeds or certain code changes can also lead to different results (the code was not yet organized when writing the paper). My suggestion is for you to take a look at my suggestions in readme and be patient. I just tried ice cream again on my own machine, but the result is not as you showed. From the results, ice cream and cars are even better than those in the paper.

![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/128572637/35ecbcc0-f0be-4e1a-8a54-27d4dea4628b)
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/128572637/6144dca2-11d7-4594-9989-5cbceb80c4e6)

Another suggestion is that you find a way to reinstall your Nvidia drivers and xformers.
