### ISSUE TITLE
About Env-Map

### ISSUE THREAD

**Issue by VLadImirluren** [Gorilla-Lab-SCUT/Fantasia3D#30]
Thanks a lot to your greate code.
I found that your code can make the environment map be learn, but no one use it, all environment are not learnable. Why? What kind of problem you meet when make it learnable?
Thanks!!!

**Comment by VLadImirluren** [comment]
非常感谢您的代码！
我发现代码中的环境光贴图可以被学习（通过将learn_light = True），但我发现所有样例没有一个将其开启。请问为什么，在开启的情况下会遇到什么麻烦？
再次感谢！！！

**Comment by ARuiChen** [comment]
You could refer to tips about using different HDR environment maps in Readme.

**Comment by VLadImirluren** [comment]
> 

thx， please forgive my carelessness
