### ISSUE TITLE
About the training of geometry_modeling

### ISSUE THREAD

**Issue by zhangxuying1004** [Gorilla-Lab-SCUT/Fantasia3D#37]
Thanks for your interesting work. I have some questions about the training of geometry modeling.
1. As shown in line 436-444 in train.py, for geometry_modeling, 'if_pretrain' is as True, and 'if_normal' is set as True, during the first 400 iterations, and 'if_pretrain' is as False, and 'if_normal' is set as True during the remaining iterations.
<img width="389" alt="截屏2023-08-18 13 50 58" src="https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/47649909/f8f7b940-34ef-492b-bac7-3eec1c391303">

However, I notice that only 'if_pretrain' and 'if_normal' are both set as True, the params of geometry will be optimized, as shown in line 478-482:
<img width="504" alt="截屏2023-08-18 14 02 37" src="https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/47649909/55272e9a-a03d-4a08-9f26-d5bdfc5a20e4">

I want to know why the model params are not optimized for the remaining iterations.

**Comment by ARuiChen** [comment]
Hi @zhangxuying1004, it is "or" not "and" in line 478. Actually, the code for line 478 should be "if FLAGS.mode == 'geometry_modeling", which would be more intuitive.
