### ISSUE TITLE
Question about user-guided generation

### ISSUE THREAD

**Issue by TLB-MISS** [Gorilla-Lab-SCUT/Fantasia3D#39]
First of all, thank you so much for sharing such amazing work!

I have a question about problem in my user-guided generation.
From what I understand, the SDF of the reference mesh is learned up to the 400th coarse iter, and from then on, 3D that fits the text is generated through SDS.
However, in my chair example, I found that the geometry suddenly completely changed after the 400th coarse iter.
Is this expected behavior? 
Of course, this problem is resolved by entering the fine iter immediately after the 400th coarse iter.
However, I wonder if it is expected behavior that the 3D geometry is changed drastically at coarse iters.

Thanks!

**coarse iter 300**
![img_geometry_modeling_000003](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/b82ba171-c88e-4485-a3e0-4f392c22e960)

**coarse iter 400**
![img_geometry_modeling_000004](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/ebe04a22-6c8a-4ec8-9cef-d7249ff98be5)

**coarse iter 500**
![img_geometry_modeling_000005](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/45352c00-ae2f-4ada-adc1-6eb6894026d7)

**Comment by ARuiChen** [comment]
This is not the expected behavior. Could you show me your configuration and the number of GPUs you have? You can try changing the seed first or let the text describe it in more detail, such as 'a back chair '; If you set 'add_directional_text=True',  ensure that the front of your chair is facing the positive half-axis of the z-axis.

**Comment by TLB-MISS** [comment]
My config

```
{
    "mode": "geometry_modeling",
    "sdf_init_shape": "custom_mesh",
    "sdf_init_shape_scale": [1.2, 1.2, 1.2],
    "random_textures": true,
    "iter": 1500,
    "coarse_iter": 1000,
    "save_interval": 100,
    "train_res": [512, 512],
    "batch": 6,
    "dmtet_grid" : 128,
    "display": [{"bsdf" : "normal"}],
    "train_background": "black",
    "validate" : true,
    "mesh_scale" : 2.4,
    "text" : "A DSLR photo of chair",
    "seed" : 42,
    "add_directional_text": false,
    "camera_random_jitter": 0.4,
    "fovy_range": [25.71, 45],
    "elevation_range": [-60, 60],
    "guidance_weight": 50
}
```

GPU : Four 3090 GPUs

Of course, when I change the seed, a different shape appears. However, even if I keep the seed the same, the results will be different every time I run it. Sometimes it comes out like the one above, and sometimes it comes out in a shape similar to the reference mesh.

**Comment by TLB-MISS** [comment]
Same seed. Rerun

**coarse iter 300**
![img_geometry_modeling_000003](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/86ef2cc4-2316-4753-b091-a1ccf6473263)

**coarse iter 400**
![img_geometry_modeling_000004](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/96b1da93-e809-4408-880d-f027685b7a2b)

**coarse iter 500**
![img_geometry_modeling_000005](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/5feb9d35-cdc2-4e09-8e72-51ccfdc1c9ef)

**Comment by ARuiChen** [comment]
1、In geometry modeling, 'a DSLR photo of ...' does not improve the results in any way.
2 、The problem of the different results using the same seed is due the the unet of stable diffusion is non-deterministic. This phenomenon has always existed and cannot be solved when using float16 precision. You can find a more stable seed to ensure that the results are basically consistent with the reference shape. 
Another suggestion is to make the text description as accurate as possible so that the topology of the result is basically the same as the reference shape.
3、The range of elevation_range, i.g. [-60,60], is so big. Why not use the default [-10,45]?

**Comment by TLB-MISS** [comment]
1, 2. Thanks for your advising!
3. I used default elevation range. But elevation range is not critical factor for consistency.

I'll change the text to be more precise! Thanks!

**Comment by TLB-MISS** [comment]
Additional Question.

I want to make even the bottom part of the mesh neat(This is why I set the elevation range large).
![Screenshot from 2023-08-31 00-29-13](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/77427895/fc8d35c4-42c0-4262-9e58-be8e7934e4ed)

But set `elevation_range` doesn't help.
What should I do to solve this?

**Comment by ARuiChen** [comment]
This is because the training data contains very few bottom perspectives. One possible solution is to include "bottom view" in the prompt word.

**Comment by TLB-MISS** [comment]
Thanks!

But, isn't `elevation_range` an option that can be set to show the bottom view?

**Comment by ARuiChen** [comment]
You should modify some codes in https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/main/sd.py#L59 and https://github.com/Gorilla-Lab-SCUT/Fantasia3D/blob/main/dataset/dataset_mesh.py#L212

**Comment by TLB-MISS** [comment]
Thanks for your advising!!
