### ISSUE TITLE
Some questions about appearance modeling

### ISSUE THREAD

**Issue by vikyzeng** [Gorilla-Lab-SCUT/Fantasia3D#4]
Congratulations on such good results! I have some questions about appearance modeling. Did you use the ordinary stable diffusion model to calculate SDS loss? Considering a fixed geometry already exists, have you used other models like depth stable diffusion to control the shape of generated images?

**Comment by ARuiChen** [comment]
That's a good question! Both geometry and appearance modeling are supervised by SDS loss using the ordinary stable diffusion model.

**Comment by vikyzeng** [comment]
Thanks for your reply! Another question is, are the parameters for SDS loss the same in both geometry modeling and appearance modeling?

**Comment by ARuiChen** [comment]
Yes!

**Comment by vikyzeng** [comment]
Can I confirm which version of stable diffusion you are using so that I can compare the results when reproducing it? Thank you very much!

**Comment by ningxinJ** [comment]
> Can I confirm which version of stable diffusion you are using so that I can compare the results when reproducing it? Thank you very much!

The version of stable diffusion is 2.1
