### ISSUE TITLE
Seed Problem

### ISSUE THREAD

**Issue by xmu-xiaoma666** [Gorilla-Lab-SCUT/Fantasia3D#40]
Hello, I ran your code twice with the same random seed on the same machine, but the results of the two runs were inconsistent. What is the reason?

**Comment by ARuiChen** [comment]
The problem of the different results using the same seed is due the the unet of stable diffusion is non-deterministic. This phenomenon has always existed and cannot be solved when using float16 precision.  #https://github.com/ashawkey/stable-dreamfusion/pull/143
From another perspective, although it may not necessarily be what we want, this inconsistency happens to give the generated results diversity.
