### ISSUE TITLE
No such file or directory: 'out/******/dmtet_mesh/mesh.obj'

### ISSUE THREAD

**Issue by QvQKing** [Gorilla-Lab-SCUT/Fantasia3D#41]
Hello, I'd like to ask, what is the cause of this error? I have tested some JSON files, and I found that a few of them have this issue of not finding the path.

Using /hy-tmp/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /hy-tmp/.cache/torch_extensions/py38_cu113/renderutils_plugin/build.ninja...
Building extension module renderutils_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module renderutils_plugin...
[INFO] loading stable diffusion...
[INFO] loaded stable diffusion!
Traceback (most recent call last):
  File "train.py", line 724, in <module>
    base_mesh = mesh.load_mesh(FLAGS.base_mesh)
  File "/hy-tmp/Fantasia3D-main/render/mesh.py", line 82, in load_mesh
    return obj.load_obj(filename, clear_ks=True, mtl_override=mtl_override)
  File "/hy-tmp/Fantasia3D-main/render/obj.py", line 35, in load_obj
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/car/dmtet_mesh/mesh.obj'

**Comment by QvQKing** [comment]
Especially in the JSON files of "mode": "appearance_modeling",.

**Comment by ARuiChen** [comment]
appearance modeling is to generate pbr texture given a mesh.
You have two choices to input the mesh:
1、 Use the mesh generated by geometry modeling. You should first generate a mesh in geometry modeling.
2、 Use custom mesh provided by yourself.
The above choices require you to provide a path for obj file. If the file in this path does not exist, the above error will be reported.

**Comment by QvQKing** [comment]
Thank you! But the following error occurred when I used python3  train.py --config configs/car_appearance_strategy0.json:
[INFO] UV padding for perturbed normal...
100%|████████████████████████████████████████████████████████████████████████████████| 16/16 [00:18<00:00,  1.16s/it]
Writing mesh:  out/car_appearance1/dmtet_mesh/mesh.obj
    writing 34000 vertices
    writing 52383 texcoords
    writing 34000 normals
    writing 68020 faces
Writing material:  out/car_appearance1/dmtet_mesh/mesh.mtl
Done exporting mesh
WARNING: FAILED to save image out/car_appearance1/dmtet_mesh/probe.hdr
The file is failed to save.

**Comment by ARuiChen** [comment]
This is strange. I have never encountered such a problem before. I guess it may be that which package is not properly installed.

**Comment by QvQKing** [comment]
> 这很奇怪。我以前从未遇到过这样的问题。我猜可能是哪个包没有安装好。

I have reinstalled all the environments according to the environment configuration in your project, but this warning still persists.
