### ISSUE TITLE
Weird pineapple texture

### ISSUE THREAD

**Issue by xiaoroubao1996** [Gorilla-Lab-SCUT/Fantasia3D#47]
It's great to see a pipeline that can generate PBR materials.
But here is my questions that I used the default parameters and config file to generate pineapple but get a result below. Did I do anything wrong?
```
# Geometry modeling. It takes about 15 minutes on 3090 GPU.
python3  train.py --config configs/pineapple_geometry_single_gpu.json
# Appearance modeling. It takes about 15 minutes on 3090 GPU.
python3  train.py --config configs/pineapple_appearance_strategy0_single_gpu.json
```
![image](https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/48600959/c4741daa-43ec-4b51-b581-3fda9f1044c1)

**Comment by ARuiChen** [comment]
I just tested it using the default parameters and found everything to be normal. I suspect it might be an issue with the environment. Did you use the Docker environment that I provided for installation? The following video is my test result. It takes 5 minutes for geometry modeling and 15 minutes for appearance modeling using a single A100.

https://github.com/Gorilla-Lab-SCUT/Fantasia3D/assets/128572637/66edbe03-2dea-4ac6-8e92-f5fa6d247d52

By the way, the default parameters for this file are from the old version, which is not the best. For geometry modeling, an additional negative prompt  "low quality" can be added; for appearance modeling, strategy 2 and the negative prompt "shadow, oversaturated, low quality, unrealistic" should be used.  If you use multiple GPUs for optimization, the result will be better.

**Comment by xiaoroubao1996** [comment]
I tried it again on the 3090 and found that the result was normal. Weird colors happen on 4090.

**Comment by A-pril** [comment]
> I tried it again on the 3090 and found that the result was normal. Weird colors happen on 4090.

Hello, I meet the same problem on both 4090 and 3090. Did you make other changes? Could you share the environment details such as the version of the packge of diffusers and xformers? Thanks a lot!!!
