### ISSUE TITLE
Comparison to Magic3D

### ISSUE THREAD

**Issue by vikyzeng** [Gorilla-Lab-SCUT/Fantasia3D#7]
Due to the mention of the inability to obtain results by optimizing meshes from scratch in Section 5 by Magic3D, what do you think is the key to the ability of Fantasia3D to directly optimize on the mesh？

**Comment by ARuiChen** [comment]
One of the advantages of Fantasia3D is applying normals and masks as latent code, which allows direct optimization of the geometry.
