### ISSUE TITLE
Some questions about Fantasia3D

### ISSUE THREAD

**Issue by raywzy** [Gorilla-Lab-SCUT/Fantasia3D#9]
Congratulations on the great work! I have two small questions:

1) Why could normal map be used to calculate the SDS loss? The SD model is trained on natural image thus intuitively it only contains the prior of the RGB photos. Do you finetune the SD model on normal maps?

2) What is the cfg value set for the two stages?

Thanks!

**Comment by ARuiChen** [comment]
Hi, @raywzy . See the previous discussion in #8

**Comment by raywzy** [comment]
@ARuiChen Thanks! And what are the cfg values?

**Comment by ARuiChen** [comment]
> @ARuiChen Thanks! And what are the cfg values?

100 for most cases.😉

**Comment by raywzy** [comment]
Thanks!!
